{
  "train-data-paths": ["/run/determined/workdir/shared_fs/data/enwik8/enwik8_text_document"],
  "valid-data-paths": ["/run/determined/workdir/shared_fs/data/enwik8/enwik8_text_document"],
  "test-data-paths": ["/run/determined/workdir/shared_fs/data/enwik8/enwik8_text_document"],
  "vocab-file": "/run/determined/workdir/shared_fs/gpt2-vocab.json",
  "merge-file": "/run/determined/workdir/shared_fs/gpt2-merges.txt",
  "save": "/tmp/checkpoints",
  "load": "/tmp/checkpoints",
  "log-dir": null,
  "hostfile": "/tmp/hostfile.txt",
  "extra_save_iters": [0]
}
